services:
  rabbitmq:
    image: rabbitmq:4.0.5-management-alpine
    hostname: rabbitmq
    restart: always
    env_file: "vars_rabbitmq.env.example"      
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq
  postgres:
    image: postgres:17.2
    restart: always
    hostname: postgres
    env_file: "vars_postgres.env.example"
    ports:
      - 5434:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  backend:
    build:
      context: /backend/
      dockerfile: Dockerfile
    image: backend
    restart: always
    env_file: "vars_backend.env.example"
    develop:
      watch:
        - path: backend/build
          action: rebuild
    ports:
      - 8081:8080
  pinger:
    build:
      context: /pinger/
      dockerfile: Dockerfile
    image: pinger
    restart: always
    env_file: "vars_pinger.env.example"
    develop:
      watch:
        - path: pinger/build
          action: rebuild
